# Generated by Django 5.2.5 on 2025-08-07 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Organization',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Organization',
            new_name='organization',
        ),
    ]
